// Generated by https://quicktype.io

export interface Vehicle {
  id:           number;
  client:       number;
  brand:        string;
  model:        string;
  year:         number;
  plate_number: string;
}
