// Generated by https://quicktype.io

export interface Vehicle {
  id:           number;
  client:       number;
  brand:        string;
  model:        string;
  year:         number;
  plate_number: string;
}

export interface User {
  user_name:    string;
  name:         string;
  last_name:    string;
  email:        string;
  number_phone: string;
}
